apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2022-02-16T14:40:53Z"
  generation: 1
  labels:
    app: demoapp
  name: demodeployment
  namespace: default
  resourceVersion: "7074640"
  uid: 103a50d5-94a0-428c-a05e-9baa3008931a
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: demoapp
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: demoapp
    spec:
      containers:
      - image: gcr.io/river-hold-340217/demowebapp@sha256:278e050f82d8589699997a076d211e2630675e3fefa339bc43cf6e1ea4904429
        imagePullPolicy: IfNotPresent
        name: demowebapp
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2022-02-16T14:40:55Z"
    lastUpdateTime: "2022-02-16T14:40:55Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2022-02-16T14:40:53Z"
    lastUpdateTime: "2022-02-16T14:40:55Z"
    message: ReplicaSet "demodeployment-8696964849" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
